require("ex.plugins")
require("ex.options")
require("ex.colors")
require("ex.keymaps")
require("ex.lualine")
require("ex.tabline")
require("ex.nvim_tree")

require("ex.autopair")
require("ex.lsp.attach")
require("ex.treesitter")
require("ex.neogit")
require("ex.context")
